server:
  port: 8080
  timeout: 10
  env: development

database:
  host: db
  port: 5432
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 300

monobank:
  api_url: https://api.monobank.ua
  webhook_url: ""  # Will be set during deployment
  request_timeout: 30

logger:
  level: debug
  encoding: json  # can be json or console
  output_paths:
    - stdout
    - /var/log/cashone/app.log
  error_output_paths:
    - stderr
    - /var/log/cashone/error.log

cors:
  allowed_origins:
    - "http://localhost:3000"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Authorization
    - Content-Type
  allow_credentials: true
  max_age: 300
