linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - deadcode
    - structcheck
    - varcheck
    - gosec
    - gocyclo
    - dupl
    - misspell
    - unparam
    - nakedret
    - prealloc
    - gocritic

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - bin
    - vendor

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
