services:
  db:
    image: postgres:15-alpine
    container_name: backend-db
    environment:
      POSTGRES_DB: ${CASHONE_DATABASE_NAME}
      POSTGRES_USER: ${CASHONE_DATABASE_USER}
      POSTGRES_PASSWORD: ${CASHONE_DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${CASHONE_DATABASE_PORT}:5432"
    networks:
      - cashone-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${CASHONE_DATABASE_USER} -d ${CASHONE_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  cashone-network:
    driver: bridge

volumes:
  postgres_data:
